/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TeachingRouteImport } from "./routes/teaching"
import { Route as SoftwareRouteImport } from "./routes/software"
import { Route as ResearchRouteImport } from "./routes/research"
import { Route as PublicationsRouteImport } from "./routes/publications"
import { Route as PostsRouteImport } from "./routes/posts"
import { Route as CvRouteImport } from "./routes/cv"
import { Route as AdminRouteImport } from "./routes/admin"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PostsSlugRouteImport } from "./routes/posts_.$slug"

const TeachingRoute = TeachingRouteImport.update({
  id: "/teaching",
  path: "/teaching",
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareRoute = SoftwareRouteImport.update({
  id: "/software",
  path: "/software",
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: "/research",
  path: "/research",
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: "/publications",
  path: "/publications",
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: "/posts",
  path: "/posts",
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: "/cv",
  path: "/cv",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: "/posts_/$slug",
  path: "/posts/$slug",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/admin": typeof AdminRoute
  "/cv": typeof CvRoute
  "/posts": typeof PostsRoute
  "/publications": typeof PublicationsRoute
  "/research": typeof ResearchRoute
  "/software": typeof SoftwareRoute
  "/teaching": typeof TeachingRoute
  "/posts/$slug": typeof PostsSlugRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/admin": typeof AdminRoute
  "/cv": typeof CvRoute
  "/posts": typeof PostsRoute
  "/publications": typeof PublicationsRoute
  "/research": typeof ResearchRoute
  "/software": typeof SoftwareRoute
  "/teaching": typeof TeachingRoute
  "/posts/$slug": typeof PostsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/admin": typeof AdminRoute
  "/cv": typeof CvRoute
  "/posts": typeof PostsRoute
  "/publications": typeof PublicationsRoute
  "/research": typeof ResearchRoute
  "/software": typeof SoftwareRoute
  "/teaching": typeof TeachingRoute
  "/posts_/$slug": typeof PostsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/admin"
    | "/cv"
    | "/posts"
    | "/publications"
    | "/research"
    | "/software"
    | "/teaching"
    | "/posts/$slug"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/admin"
    | "/cv"
    | "/posts"
    | "/publications"
    | "/research"
    | "/software"
    | "/teaching"
    | "/posts/$slug"
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/cv"
    | "/posts"
    | "/publications"
    | "/research"
    | "/software"
    | "/teaching"
    | "/posts_/$slug"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CvRoute: typeof CvRoute
  PostsRoute: typeof PostsRoute
  PublicationsRoute: typeof PublicationsRoute
  ResearchRoute: typeof ResearchRoute
  SoftwareRoute: typeof SoftwareRoute
  TeachingRoute: typeof TeachingRoute
  PostsSlugRoute: typeof PostsSlugRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/teaching": {
      id: "/teaching"
      path: "/teaching"
      fullPath: "/teaching"
      preLoaderRoute: typeof TeachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/software": {
      id: "/software"
      path: "/software"
      fullPath: "/software"
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/research": {
      id: "/research"
      path: "/research"
      fullPath: "/research"
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/publications": {
      id: "/publications"
      path: "/publications"
      fullPath: "/publications"
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/posts": {
      id: "/posts"
      path: "/posts"
      fullPath: "/posts"
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/cv": {
      id: "/cv"
      path: "/cv"
      fullPath: "/cv"
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin": {
      id: "/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/posts_/$slug": {
      id: "/posts_/$slug"
      path: "/posts/$slug"
      fullPath: "/posts/$slug"
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CvRoute: CvRoute,
  PostsRoute: PostsRoute,
  PublicationsRoute: PublicationsRoute,
  ResearchRoute: ResearchRoute,
  SoftwareRoute: SoftwareRoute,
  TeachingRoute: TeachingRoute,
  PostsSlugRoute: PostsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
